[package]
name = "miniMenu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ncurses = "5.101.0"
lazy_static = "1.4.0"
cargo-watch = "8.4.1"
