[package]
name = "miniMenu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
walkdir = "2.5.0"
ncurses = "5.101.0"
sysinfo = "0.26.6"
nix = { version = "0.25.0", features = ["ptrace"] }
